---
title: "fpp-ch-9"
output: html_document
date: "2023-02-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Qn 2

The plots below show that there is high level of correlation between the previous level of the stock and the next level of the stock, indicating that we should take a first difference.

```{r}

gafa_stock %>% distinct(Symbol)

a_stock <- gafa_stock %>% 
  filter(Symbol == "AMZN")

a_stock %>% 
  ACF() %>% 
  autoplot()

a_stock %>% 
  PACF() %>% 
  autoplot()
```

# Qn 3

```{r}

global_economy %>% head()
global_economy %>% distinct(Country)

turkey_ec <- global_economy %>% 
  filter(Country == "Turkey")

turkey_ec %>% autoplot(GDP)
turkey_ec %>% autoplot(difference(GDP))

turk_feat <- turkey_ec %>%
  features(GDP, features = guerrero)
(lambda <- turk_feat %>%
  pull(lambda_guerrero))

turkey_ec %>%
  autoplot(box_cox(GDP, lambda))

turkey_ec <- turkey_ec %>% 
  mutate(box_cox_gdp = box_cox(GDP, lambda)) %>% 
  mutate(diff_box_cox_gdp = difference(box_cox_gdp))

head(turkey_ec)

turkey_ec %>% autoplot(diff_box_cox_gdp)

# add do stationarity test
```
